#!/usr/bin/env python3
"""src/ を1枚のHTMLに束ねる。
  public/index.html … 公開用（Cloudflare Workers が配信する完全なページ）
  artifact.html     … Artifact 用の本文断片（<head>骨格はホスト側が付ける）
"""
import pathlib

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / 'src'
URL = 'https://drone-anatomy-3d.hiro-k61.workers.dev/'
DESC = ('ドローン（550クラスのクアッドコプター）を部品ごとに分解・透視・断面表示できる3D教材。'
        '40種の部品それぞれに役割・構造・仕様例・点検ポイントの解説と、飛行の原理のアニメーションがついています。')

tpl = (SRC / 'index.html').read_text(encoding='utf-8')
css = (SRC / 'style.css').read_text(encoding='utf-8')
# CSS のコメントが閉じているか検査する（閉じ忘れると以降の宣言がまとめて無効になる）
_i = 0
while True:
    _a = css.find('/*', _i)
    if _a < 0:
        break
    _b = css.find('*/', _a + 2)
    if _b < 0:
        raise SystemExit('style.css: コメントが閉じていません (行 %d)' % (css[:_a].count(chr(10)) + 1))
    if css[_a:_b].count(chr(10)) > 2:
        raise SystemExit('style.css: コメントが %d 行にまたがっています (行 %d) — 閉じ忘れの疑い' % (css[_a:_b].count(chr(10)) + 1, css[:_a].count(chr(10)) + 1))
    _i = _b + 2
SOURCES = ['data.js', 'materials.js', 'drone.js', 'engine.js', 'physics.js', 'airflow.js', 'theater.js', 'whatif.js', 'scale.js', 'codex.js', 'live.js', 'lesson.js', 'expert.js', 'reg.js', 'ui.js', 'app.js']
js = '\n'.join((SRC / f).read_text(encoding='utf-8') for f in SOURCES if (SRC / f).exists())

frag = tpl.replace('/*INLINE:style.css*/', css).replace('/*INLINE:scripts*/', js)
# 出力は決定的にする（日付などを混ぜると CI の差分検査が誤検知する）
frag = frag.replace('<title>ドローンの構造</title>',
                    '<title>ドローンの構造</title>\n<!-- generated by build.py from src/ — このファイルを直接編集しないこと -->', 1)
(ROOT / 'artifact.html').write_text(frag, encoding='utf-8')

head = f'''<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<meta name="description" content="{DESC}">
<meta property="og:type" content="website">
<meta property="og:title" content="ドローンの構造">
<meta property="og:description" content="{DESC}">
<meta property="og:url" content="{URL}">
<meta property="og:locale" content="ja_JP">
<meta name="twitter:card" content="summary">
<link rel="canonical" href="{URL}">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ctext y='.9em' font-size='90'%3E%F0%9F%9B%B8%3C/text%3E%3C/svg%3E">
</head>
<body>
'''
(ROOT / 'public' / 'index.html').write_text(head + frag + '\n</body>\n</html>\n', encoding='utf-8')

for p in [ROOT / 'public' / 'index.html', ROOT / 'artifact.html']:
    print(f'{p.relative_to(ROOT)}  {p.stat().st_size // 1024} KB')
