// ===== 部品データ（解説・仕様例・点検ポイント） =====
// 数値は「550クラス産業用クアッドコプターの典型例」。実機に合わせて差し替え可。
const GROUPS = [
  { id: 'frame',   name: '機体構造',   color: '#8b939f' },
  { id: 'prop',    name: '推進系',     color: '#ef6a2d' },
  { id: 'elec',    name: '電装',       color: '#3b7df7' },
  { id: 'nav',     name: '航法・通信', color: '#14b8a6' },
  { id: 'payload', name: 'ペイロード', color: '#a06cf5' },
  { id: 'gear',    name: '降着装置',   color: '#6b7280' },
];

const PARTS = {
  frameTop: {
    name: '上部プレート', en: 'Top plate', group: 'frame', count: 1,
    role: '機体の骨格の上面。下部プレートとの間にアームクランプを挟み込んで固定し、GPSマストや送信機など上に載せる機器の取付面にもなる。',
    structure: ['カーボン繊維強化樹脂(CFRP)の板。綾織(ツイル)の織り目が見える', '中央の切り欠きは配線の通し穴と軽量化のため', 'スタンドオフ(支柱)で下部プレートと結合'],
    spec: [['材質', 'CFRP 綾織 2.0mm'], ['寸法', '150 × 150 mm'], ['質量', '約 45 g']],
    check: ['ひび割れ・層間はく離(白く濁った部分)', 'ネジのゆるみ、脱落', 'アーム固定部のガタつき'],
    tip: 'カーボンは軽く剛性が高い一方、導電性があるため基板やアンテナが直接触れないように絶縁する。',
  },
  frameBottom: {
    name: '下部プレート', en: 'Bottom plate', group: 'frame', count: 1,
    role: '骨格の底面。バッテリー、降着装置、ジンバルの取付面。着陸の衝撃を最初に受ける部材。',
    structure: ['上部より厚い2.5mmで、荷重を受け持つ', 'バッテリーストラップを通すスロットがある', '前方に張り出してジンバルの取付面を確保'],
    spec: [['材質', 'CFRP 綾織 2.5mm'], ['寸法', '150 × 170 mm'], ['質量', '約 70 g']],
    check: ['着陸衝撃によるクラック(特に脚の取付部周辺)', 'ストラップ穴の摩耗', 'ジンバル取付ネジのゆるみ'],
  },
  arm: {
    name: 'アーム', en: 'Arm (CFRP tube)', group: 'frame', count: 4,
    role: 'モーターを機体中心から等距離・同一平面に保持する。アームの剛性が足りないと振動がIMUに乗り、姿勢制御が乱れる。',
    structure: ['φ16mmのカーボン丸パイプ', '中心側はクランプで、先端側はモーターマウントで固定', '上面に沿ってESCとモーターの配線を這わせる'],
    spec: [['材質', 'CFRP 丸パイプ φ16 × 1.0t'], ['長さ', '245 mm'], ['対角モーター間距離', '550 mm']],
    check: ['曲がり・割れ、繊維のささくれ', 'クランプ部での回転ズレ(モーター面が水平か)', '配線が擦れて被覆が傷んでいないか'],
    tip: 'モーター間隔(対角)がフレームの「クラス」名になる。550クラスなら対角550mm。',
  },
  armClamp: {
    name: 'アームクランプ', en: 'Arm clamp', group: 'frame', count: 4,
    role: 'アームを上下プレートの間で挟み込んで固定する部品。アームの角度と水平を決める基準。',
    structure: ['アルミ削り出し(アルマイト処理)', '上下からM3ボルト各2本で締結'],
    spec: [['材質', 'A6061 アルマイト'], ['締結', 'M3 × 4本']],
    check: ['ボルトの締付トルク(ネジロック剤の有無)', 'クランプの割れ'],
  },
  motorMount: {
    name: 'モーターマウント', en: 'Motor mount', group: 'frame', count: 4,
    role: 'アーム先端でモーターを受ける座面。航法灯(LED)もここに組み込まれる。',
    structure: ['アルミ製のクランプブロックと円形の座面', 'モーターはM3ボルト4本で固定'],
    spec: [['材質', 'A6061 アルマイト'], ['ボルト', 'M3 × 4本 / モーター']],
    check: ['モーター固定ボルトのゆるみ(振動で緩みやすい)', '座面の変形'],
  },
  standoff: {
    name: 'スタンドオフ', en: 'Standoff', group: 'frame', count: 8,
    role: '上下プレートの間隔を保ち、両者を結合する支柱。',
    structure: ['六角のアルミ支柱。両端にM3ネジ穴'],
    spec: [['長さ', '35 mm'], ['材質', 'アルミ アルマイト']],
    check: ['ゆるみ(手でプレートをねじって動かないか)'],
  },
  screws: {
    name: 'ネジ類', en: 'Fasteners', group: 'frame', count: 1,
    role: '各部を締結するM3ボルト。振動環境なのでネジロック剤が必須。',
    structure: ['六角穴付きボタンボルト(M3)', 'モーター固定用は長さに注意(長すぎると巻線に達して短絡する)'],
    spec: [['サイズ', 'M3 × 6〜10 mm'], ['材質', 'ステンレス / スチール']],
    check: ['ゆるみ・脱落', 'ネジ頭の舐め'],
  },

  motor: {
    name: 'ブラシレスモーター', en: 'Brushless outrunner motor', group: 'prop', count: 4,
    role: 'ESCから供給される三相交流で回転し、プロペラを回す。外側の缶(ローター)が回転し、内側のステーター(固定子)は動かない「アウターランナー」型。',
    structure: ['ローター(ベル): 内周に永久磁石14個。上面に放熱スリット', 'ステーター: 12極の積層鉄心にエナメル銅線を巻いたコイル', 'シャフトは2個のベアリングで支持。摩耗部品はベアリングだけ'],
    spec: [['サイズ', '2814 (ステーター径28mm・高さ14mm)'], ['KV値', '450 KV (1Vあたりの無負荷回転数)'], ['極数', '12N14P'], ['最大電流', '25 A'], ['質量', '約 95 g']],
    check: ['指で回してゴリゴリ感・引っかかりがないか(ベアリング)', 'シャフトのガタ・曲がり', '砂・草・糸くずの噛み込み', 'コイルの変色(過熱の痕跡)'],
    tip: '回転方向は3本の相線のうち2本を入れ替えるか、ESCの設定で反転できる。ブラシがないため火花が出ず、寿命が長い。',
  },
  bell: {
    name: 'ローター(ベル)', en: 'Rotor bell', group: 'prop', count: 4,
    role: 'モーターの回転する外殻。内周に貼られた永久磁石がステーターの磁界に引かれて回る。',
    structure: ['アルミ削り出しの缶。側面と上面のスリットは冷却用', '中央のハブにシャフトを圧入'],
    spec: [['外径', '35 mm'], ['磁石', 'ネオジム × 14']],
    check: ['スリットからの異物混入', '磁石のはがれ・ひび(回すとコツコツ音)'],
  },
  stator: {
    name: 'ステーター(固定子)', en: 'Stator', group: 'prop', count: 4,
    role: 'コイルを巻いた12極の鉄心。ESCが順番に電流を流すと回転磁界ができ、ローターを引き回す。',
    structure: ['0.2mm厚のケイ素鋼板を積層(渦電流損を減らす)', '各極の先端は「シュー」と呼ばれる広がりで磁束を集める'],
    spec: [['極数', '12'], ['積層', 'ケイ素鋼板 0.2mm']],
    check: ['絶縁被膜の傷(短絡の原因)'],
  },
  winding: {
    name: '巻線(コイル)', en: 'Windings', group: 'prop', count: 4,
    role: 'エナメル被覆の銅線。U・V・Wの3相に分けて巻かれ、順に通電されて回転磁界を作る。',
    structure: ['3相 × 4極 = 12極。相ごとに結線(スター結線)', '線径が太いほど大電流に耐え、巻数が少ないほどKV値が上がる'],
    spec: [['線材', 'エナメル銅線'], ['相数', '3相 (U/V/W)']],
    check: ['焦げ・変色(過熱)', 'エナメルのはがれ'],
    tip: 'モーターの発熱の大半はここ。長時間のホバリング後は触って温度を確かめる習慣を。',
  },
  magnet: {
    name: '永久磁石', en: 'Permanent magnets', group: 'prop', count: 4,
    role: 'ローター内周にN極・S極が交互になるよう14個並ぶ。ステーターの回転磁界と引き合い/反発してトルクを生む。',
    structure: ['ネオジム磁石(強力だが熱に弱い)', '接着剤でベル内周に固定'],
    spec: [['個数', '14 (N/S 交互)'], ['材質', 'ネオジム (NdFeB)']],
    check: ['はがれ・欠け(異音の原因)', '高温での減磁(推力低下)'],
  },
  shaft: {
    name: 'シャフト・ベアリング', en: 'Shaft & bearings', group: 'prop', count: 4,
    role: 'ローターの回転をプロペラへ伝える軸。ベースの2つのボールベアリングで支えられる。',
    structure: ['硬化鋼のシャフト φ4mm', '下端のCリングで抜け止め'],
    spec: [['シャフト径', '4 mm'], ['ベアリング', '2 個']],
    check: ['軸方向のガタ(上下に引いて動く)', '回転時の異音・振動'],
  },
  motorBase: {
    name: 'モーターベース', en: 'Motor base', group: 'prop', count: 4,
    role: 'ステーターとベアリングを保持し、モーターマウントに固定される土台。',
    structure: ['アルミ削り出し。十字の腕に取付穴', '相線はここから引き出される'],
    spec: [['取付', 'M3 × 4 (16/19mm ピッチ)']],
    check: ['取付面の歪み', '相線の付け根の被覆'],
  },
  prop: {
    name: 'プロペラ', en: 'Propeller', group: 'prop', count: 4,
    role: '回転して空気を下向きに押し、その反作用として揚力(推力)を得る。翼にはねじれ(ピッチ)があり、根元ほど迎え角が大きい。',
    structure: ['隣り合うモーターは逆回転。時計回り(CW)用と反時計回り(CCW)用が2枚ずつある', '表面の刻印「12×4.5」は直径12インチ・ピッチ4.5インチ', '翼断面は薄い翼型で、先端ほど薄く細い'],
    spec: [['サイズ', '12 × 4.5 インチ (直径 305mm / ピッチ 114mm)'], ['翼数', '2'], ['材質', 'ガラス繊維強化ナイロン'], ['質量', '約 20 g（ナット・アダプター込みで約 29 g）']],
    check: ['欠け・ひび・曲がり(小さな傷でも振動が増え、飛行中に破断することがある)', 'ナットの締付', '回転方向(CW/CCW)が正しいか、刻印が上を向いているか', '左右の重量バランス(振動)'],
    tip: '取付を間違えると離陸直後に機体が反転する。飛行前点検で最重要の部品のひとつ。',
  },
  propNut: {
    name: 'プロペラナット', en: 'Prop nut', group: 'prop', count: 4,
    role: 'プロペラをモーターに固定するナット。回転で締まる方向のねじ(セルフタイトニング)が使われることが多い。',
    structure: ['CW用とCCW用でねじの向きが逆(逆ねじ)の製品もある'],
    spec: [['ねじ', 'M6 (自締式)']],
    check: ['締付(工具で確実に)', 'ねじ山の摩耗'],
  },
  esc: {
    name: 'ESC', en: 'Electronic Speed Controller', group: 'prop', count: 4,
    role: 'フライトコントローラーからの指令(DShot等の信号)に応じて、バッテリーの直流を三相交流に変換しモーターへ流す。回転数を毎秒数万回のスイッチングで制御する。',
    structure: ['基板上のMOSFET 6個が電流をスイッチング', '熱収縮チューブで絶縁', 'モーター側に3本、電源側に2本、信号線1本'],
    spec: [['連続電流', '40 A'], ['対応電圧', '3〜6S'], ['ファームウェア', 'BLHeli_32'], ['プロトコル', 'DShot600']],
    check: ['熱収縮チューブの破れ', 'はんだのクラック(相線の付け根)', '発熱・焦げ跡', '出力が1つだけ弱くないか(ホバリング時の傾き)'],
    tip: 'ESCが1基故障するとクアッドコプターは制御を失い墜落する。ヘキサ(6発)以上なら1基喪失でも着陸できる場合がある。',
  },

  fc: {
    name: 'フライトコントローラー', en: 'Flight controller', group: 'elec', count: 1,
    role: '機体の頭脳。IMUで姿勢を毎秒数千回読み取り、操縦入力と比較して4つのモーターの回転数を計算しESCに指令する。',
    structure: ['MCU(マイコン)が制御ループを実行', 'IMU(3軸ジャイロ+3軸加速度)は防振ゴムで振動から隔離', '気圧計で高度を推定。GPS・受信機・テレメトリはUART接続', 'フライトログ(ブラックボックス)をフラッシュメモリに記録'],
    spec: [['MCU', 'STM32 F7 (216 MHz)'], ['IMU', '3軸ジャイロ + 3軸加速度'], ['気圧計', 'あり'], ['取付', '30.5 × 30.5 mm 穴ピッチ']],
    check: ['防振グロメットの劣化・つぶれ', 'USBコネクタの割れ', 'ファームウェア更新後の設定(機体の向き・モーター順序)の再確認'],
    tip: '基板上の矢印は機首方向。向きを間違えて取り付けると離陸直後にひっくり返る。',
  },
  pdb: {
    name: '電源分配基板', en: 'Power distribution board', group: 'elec', count: 1,
    role: 'バッテリーの電力を4つのESCと、5V/12Vに降圧してFC・受信機・カメラへ分配する。電流と電圧を測ってテレメトリに送る。',
    structure: ['厚い銅箔のパッドに太い電源線をはんだ付け', 'BEC(降圧回路)と電流センサーを内蔵'],
    spec: [['最大電流', '120 A'], ['BEC出力', '5V 3A / 12V 2A']],
    check: ['はんだ部の変色・クラック', '電流センサーの校正(表示と実測のズレ)'],
  },
  capacitor: {
    name: 'コンデンサ', en: 'Low-ESR capacitor', group: 'elec', count: 1,
    role: 'ESCのスイッチングで発生する電圧のスパイクを吸収し、FCや映像のノイズを減らす。',
    structure: ['低ESRの電解コンデンサを電源入力の直近に'],
    spec: [['容量', '1000 µF / 35V']],
    check: ['膨らみ・液漏れ'],
  },
  buzzer: {
    name: 'ブザー', en: 'Buzzer', group: 'elec', count: 1,
    role: '警告音(バッテリー低下・アーム状態)と、墜落時に機体を探すためのロストモデルアラーム。',
    structure: ['圧電ブザー。FCから駆動'],
    spec: [['音量', '約 100 dB']],
    check: ['発音の確認(起動時)'],
  },
  battery: {
    name: 'バッテリー(LiPo)', en: 'LiPo battery', group: 'elec', count: 1,
    role: '全システムの電源。この機体では重量の約4分の1（機種によっては3〜4割）を占め、飛行時間を決める。',
    structure: ['リチウムポリマー(LiPo)セルを6枚直列(6S)', '太い電源線(XT60コネクタ)と、セルごとの電圧を測るバランスコネクタ', '2本のストラップで下部プレートに固定'],
    spec: [['構成', '6S (22.2V, 満充電 25.2V)'], ['容量', '5,000 mAh (111 Wh)'], ['放電レート', '25C (連続 125A)'], ['質量', '約 640 g']],
    check: ['膨らみ(少しでもあれば使用中止)', '外装の傷・へこみ', 'コネクタの焼け・ゆるみ', 'セル間電圧差(0.05V以上で要注意)', '保管は 3.8V/セル前後で'],
    tip: 'セル電圧が3.0Vを下回ると劣化が急速に進む。飛行中は3.5V/セルを目安に着陸する。',
  },
  cells: {
    name: 'セル(内部)', en: 'Cells', group: 'elec', count: 1,
    role: 'バッテリー内部のパウチ型セル。1セルの公称電圧3.7Vを6枚直列にして22.2Vを得る。',
    structure: ['アルミラミネートの袋(パウチ)に電極を封入', 'セル同士はニッケルタブで直列接続'],
    spec: [['セル電圧', '3.7V (3.0〜4.2V)'], ['枚数', '6']],
    check: ['断面表示モードで内部構造を確認できる'],
  },
  xt60: {
    name: 'XT60コネクタ', en: 'XT60 connector', group: 'elec', count: 1,
    role: 'バッテリーと機体の電源を接続する大電流コネクタ。極性を間違えない形状。',
    structure: ['黄色のナイロン筐体に金メッキ端子'],
    spec: [['定格', '60 A 連続']],
    check: ['端子の変色・焼け', '差し込みのゆるさ(発熱の原因)'],
  },
  balance: {
    name: 'バランスコネクタ', en: 'Balance lead', group: 'elec', count: 1,
    role: 'セルごとの電圧を測り、充電時に全セルを均等(バランス)に充電するための細い配線。',
    structure: ['7本(6S用)の細線とJST-XHコネクタ'],
    spec: [['コネクタ', 'JST-XH 7ピン']],
    check: ['断線・被覆の傷(短絡すると発火の危険)'],
  },
  strap: {
    name: 'バッテリーストラップ', en: 'Battery strap', group: 'elec', count: 2,
    role: 'バッテリーを機体に固定するベルト。飛行中にバッテリーがずれると重心が動き、最悪落下する。',
    structure: ['滑り止め付きの面ファスナーベルト'],
    spec: [['幅', '20 mm']],
    check: ['面ファスナーの劣化(保持力)', 'ゴムの滑り止めの摩耗'],
  },
  wiring: {
    name: '配線', en: 'Wiring', group: 'elec', count: 1,
    role: '電源線(バッテリー→PDB→ESC)、相線(ESC→モーター 3本)、信号線(FC→ESC/受信機/GPS)の3系統。',
    structure: ['電源線は太い(12〜14AWG)シリコン被覆線', '相線は3本一組。振動で擦れないよう結束バンドで固定', '信号線は細く、電源線から離して引く(ノイズ対策)'],
    spec: [['電源線', '12 AWG'], ['相線', '18 AWG'], ['信号線', '28 AWG']],
    check: ['被覆の擦れ・切れ', 'コネクタの抜けかけ', '結束バンドのゆるみ'],
  },

  gps: {
    name: 'GNSS / コンパス', en: 'GNSS & compass module', group: 'nav', count: 1,
    role: '衛星測位で位置と速度を、地磁気センサーで機首方位を測る。位置保持(GPSモード)、自動帰還(RTH)、ウェイポイント飛行の要。',
    structure: ['円盤の中にセラミックパッチアンテナと受信IC', 'モーターや電源線の磁界から離すためマストで持ち上げる', '筐体の矢印を機首方向に合わせて取り付ける'],
    spec: [['衛星系', 'GPS / GLONASS / Galileo / BeiDou / みちびき(QZSS)'], ['更新レート', '10 Hz'], ['コンパス', '3軸 地磁気センサー']],
    check: ['マストの固定・折れ', 'コンパスのキャリブレーション要否(場所を大きく変えたとき)', '離陸前の受信衛星数(目安 12以上)'],
    tip: '衛星を失うと位置保持ができず、姿勢のみの制御(ATTIモード)になり風に流される。手動で戻せる技量が求められる理由。',
  },
  rx: {
    name: '受信機とアンテナ', en: 'Receiver (RX)', group: 'nav', count: 1,
    role: '送信機(プロポ)からの操縦信号を受け取り、FCへ渡す。電波が途絶えたときはフェイルセーフ(ホバリング/帰還/着陸)を発動させる。',
    structure: ['2本のアンテナを90°に開く「ダイバーシティ」で電波の向きによる感度低下を防ぐ', 'アンテナ先端(裸の導体部分)をカーボンフレームから離す'],
    spec: [['周波数', '2.4 GHz'], ['アンテナ', 'ダイバーシティ × 2'], ['通信', 'SBUS / CRSF']],
    check: ['アンテナ被覆の破れ・折れ', 'フェイルセーフ設定の確認(送信機の電源を切って挙動を見る)'],
    tip: 'カーボンは電波を遮る。アンテナが機体に隠れると通信距離が大きく落ちる。',
  },
  vtx: {
    name: '映像送信機', en: 'Video transmitter (VTX)', group: 'nav', count: 1,
    role: 'カメラの映像と機体データ(テレメトリ)を地上局へ送る。',
    structure: ['きのこ型の円偏波アンテナ', '発熱が大きく、モーターの風が当たる位置に置く'],
    spec: [['周波数', '5.8 GHz'], ['出力', '25 〜 600 mW']],
    check: ['アンテナ未接続での送信(出力段が壊れる)', '発熱'],
  },
  led: {
    name: '航法灯(LED)', en: 'Navigation lights', group: 'nav', count: 4,
    role: '遠くからでも機首の向きと姿勢を判別するための灯火。',
    structure: ['航空機の航法灯にならい、前方左を赤・右を緑、後方を白にした例', '市販機では「前赤・後緑」など配色がメーカーごとに違うので取扱説明書で確認'],
    spec: [['前左', '赤'], ['前右', '緑'], ['後', '白 (点滅)']],
    check: ['点灯・点滅の確認', '夜間飛行では機体の姿勢と方向が視認できる灯火が必要(承認基準)'],
  },

  damper: {
    name: '防振ダンパー', en: 'Vibration dampers', group: 'payload', count: 4,
    role: 'モーター振動がカメラに伝わるのを遮断するゴム球。映像の「こんにゃく現象」を防ぐ。',
    structure: ['シリコンゴムのボール4個で吊り下げ板を支える'],
    spec: [['硬度', 'ペイロード重量に合わせて選ぶ']],
    check: ['ゴムの劣化・ひび', '伸びきり・外れ'],
  },
  gimbal: {
    name: '3軸ジンバル', en: '3-axis gimbal', group: 'payload', count: 1,
    role: '機体の揺れを3つのブラシレスモーター(ヨー/ロール/ピッチ)で瞬時に打ち消し、カメラを常に水平・狙った向きに保つ。',
    structure: ['ジンバル自体にもIMUがあり、独立した制御ループで動く', 'ヨー軸(垂直) → ロール軸(前後) → ピッチ軸(左右)の順に腕がつながる'],
    spec: [['軸', 'ヨー / ロール / ピッチ'], ['制御角', 'ピッチ -90°〜+30°']],
    check: ['各軸を手で動かして引っかかりがないか', 'ケーブルの噛み込み', '起動時の水平出し'],
  },
  camera: {
    name: 'カメラ', en: 'Camera', group: 'payload', count: 1,
    role: '空撮・点検の目的そのもの。ジンバルに吊られ、地上の送信機からピッチとシャッターを操作する。',
    structure: ['1インチセンサーと固定焦点レンズ', '映像は映像送信機を通じて地上へ'],
    spec: [['センサー', '1 インチ 20 MP'], ['動画', '4K / 60fps'], ['質量', '約 250 g (ジンバル込み)']],
    check: ['レンズの汚れ・傷', 'メモリーカードの残量', '固定ネジ'],
  },

  propAdapter: {
    name: 'プロペラアダプター', en: 'Prop adapter', group: 'prop', count: 4,
    role: 'モーターのベル天面にネジ止めされ、プロペラを載せる座とM6のねじ軸を提供する部品。',
    structure: ['φ14の座と長さ17mmのねじ軸', 'ベルに4本の小ネジで固定される'],
    spec: [['ねじ', 'M6'], ['固定', 'M3 × 4']],
    check: ['ねじ軸の曲がり（プロペラの面ぶれ）', '固定ネジのゆるみ'],
  },
  batteryTray: {
    name: 'バッテリートレイ', en: 'Battery tray', group: 'elec', count: 1,
    role: 'バッテリーを受けるカーボンの板。表面のすべり止めゴムが振動でのずれを防ぐ。',
    structure: ['CFRP 2mm + EVAスポンジ3mm', 'ストラップを通すスロット付き'],
    spec: [['寸法', '60 × 170 mm']],
    check: ['スポンジの劣化・はがれ', 'スロットの摩耗'],
  },
  remoteId: {
    name: 'リモートID', en: 'Remote ID module', group: 'nav', count: 1,
    role: '機体の登録記号・位置・速度などを電波で発信する装置。地上から誰の機体かを識別できるようにする。100g以上の機体は原則として搭載が義務。',
    structure: ['小型の樹脂ケースに無線モジュールとアンテナ', 'FCから電源と位置情報を受ける'],
    spec: [['方式', 'Bluetooth 5 / Wi-Fi Beacon'], ['発信間隔', '1 秒']],
    check: ['発信状態のLED', 'アプリで受信できるか', '登録記号との紐づけ'],
    tip: '内蔵型の機体は別売りの外付けモジュールが不要。搭載免除の条件（係留飛行・登録講習機関の講習など）もある。',
  },
  regMark: {
    name: '登録記号の表示', en: 'Registration mark', group: 'frame', count: 1,
    role: '国土交通省に登録した機体の記号（JU〜）を機体表面に表示するラベル。',
    structure: ['耐候性のラベルに文字高3mm以上で表示', '外から見える位置に貼る'],
    spec: [['文字の高さ', '3 mm 以上（25kg以上は25mm以上）'], ['位置', '機体表面の外から見える場所']],
    check: ['文字がかすれていないか', 'はがれ'],
  },
  telemetry: {
    name: 'テレメトリー無線機', en: 'Telemetry radio', group: 'nav', count: 1,
    role: '機体の姿勢・電圧・位置などのデータを地上局（パソコンやタブレット）とやり取りする無線機。自動飛行の指令もここを通る。',
    structure: ['無線モジュールとダイポールアンテナ'],
    spec: [['周波数', '2.4 GHz'], ['通信', 'MAVLink']],
    check: ['アンテナの固定', 'リンク品質の確認'],
  },

  landingGear: {
    name: '降着装置(スキッド)', en: 'Landing skids', group: 'gear', count: 2,
    role: '離着陸時に機体を支え、ジンバルとカメラを地面から守る。',
    structure: ['カーボンパイプの脚2本とスキッド(そり)1本で片側を構成', '先端にゴムキャップ。着陸の衝撃はここと下部プレートで受ける'],
    spec: [['材質', 'CFRP φ10mm'], ['地上高', '150 mm']],
    check: ['パイプの割れ', '取付部のゆるみ', 'ゴムキャップの脱落'],
  },
};

// ===== 飛行の原理デモ =====
// mult: モーター M1(前右) M2(後右) M3(後左) M4(前左) の回転数倍率
const FLIGHT = {
  hover: { name: 'ホバリング', mult: [1, 1, 1, 1],
    note: '4つのモーターが同じ推力を出し、合計が機体重量と釣り合うと空中で静止する。隣同士が逆回転なので反トルクも打ち消し合う。' },
  climb: { name: '上昇', mult: [1.25, 1.25, 1.25, 1.25],
    note: '4つとも同時に増速。合計推力が重量を上回ると上昇し、減速すれば下降する。姿勢は変わらない。' },
  pitch: { name: '前進', mult: [0.85, 1.15, 1.15, 0.85],
    note: '後ろ2つ(M2・M3)を増速、前2つを減速すると機首が下がる。推力が前に傾き、その水平成分で前進する。' },
  roll: { name: '右へ移動', mult: [0.85, 0.85, 1.15, 1.15],
    note: '左2つ(M3・M4)を増速、右2つを減速すると機体が右に傾き、右へ移動する。前進と原理は同じで軸が違うだけ。' },
  yaw: { name: '右旋回(ヨー)', mult: [1.15, 0.85, 1.15, 0.85],
    note: '反時計回りのモーター(M1・M3)を増速し、時計回り(M2・M4)を減速。反トルクの釣り合いが崩れ、機体が時計回りに回る。推力の合計は変わらないので高度は保たれる。' },
};

const MOTOR_INFO = [
  { id: 'M1', pos: '前右', dir: 'CCW' },
  { id: 'M2', pos: '後右', dir: 'CW' },
  { id: 'M3', pos: '後左', dir: 'CCW' },
  { id: 'M4', pos: '前左', dir: 'CW' },
];

// ===== はじめてモード: 8部品の平易な説明とたとえ話 =====
const SIMPLE = {
  prop:        { role: '回って空気を下に押します。その反動で機体が浮きます。', analogy: '扇風機の羽根を下に向けて、自分が浮くようなもの' },
  motor:       { role: 'プロペラを回す力の元です。1分間に数千回まわります。', analogy: 'ミニ四駆のモーターを、もっと強く静かにしたもの' },
  arm:         { role: 'モーターを機体の真ん中から同じ距離に支える棒です。', analogy: '天秤の腕。左右の長さが同じだから釣り合う' },
  frameTop:    { role: '機体の骨格。すべての部品はここに取り付けられています。', analogy: '人の背骨と肋骨' },
  battery:     { role: '全部の電気のもと。機体で一番重い部品で、値段も高いほうです。', analogy: 'スマホの電池 8台分くらいの電気を、1つにまとめたもの' },
  fc:          { role: '機体の頭脳。傾きを毎秒何千回も測って、4つのモーターの速さを決めます。', analogy: '自転車に乗るときの「小脳」。倒れそうになると勝手に直す' },
  landingGear: { role: '着陸のときに機体とカメラを地面から守る脚です。', analogy: '飛行機の車輪。でも転がらずに、そりで滑る' },
  camera:      { role: '空から写真や映像をとる目です。下のジンバルが揺れを打ち消します。', analogy: 'カメラマンが息を止めて撮るのを、機械が代わりにやる' },
};
const SIMPLE_KEYS = Object.keys(SIMPLE);
// ラベル簡略名（はじめて用）
const SIMPLE_NAME = { prop: 'プロペラ', motor: 'モーター', arm: 'アーム', frameTop: 'フレーム', battery: 'バッテリー', fc: '頭脳（FC）', landingGear: '脚', camera: 'カメラ' };

// ===== 用途から入る扉: 部品の3分類（共通 / 強化 / 追加） =====
// keep: 今の機体のまま使う部品 / up: 同じ役割だが大型化・強化される / ghost: 新たに載る物（機体に半透明で重ねる）
const USES = [
  { id: 'disaster', name: '防災', tagline: '被災地の状況を上から確かめ、声を届ける',
    up: ['battery', 'led', 'vtx', 'landingGear', 'gps'],
    ghost: [
      { id: 'speaker', name: '拡声器（スピーカー）', shape: 'box', size: [0.10, 0.06, 0.06], pos: [0, -0.06, 0.06], note: '住民への呼びかけ。約400 g' },
      { id: 'thermal', name: '赤外線（サーマル）カメラ', shape: 'box', size: [0.05, 0.04, 0.05], pos: [0.05, -0.10, -0.085], note: '夜間や煙の中でも人を探す' },
      { id: 'light', name: '投光器', shape: 'cyl', size: [0.03, 0.05], pos: [-0.06, -0.06, -0.06], note: '夜間の捜索・作業の照明' },
      { id: 'chute', name: 'パラシュート', shape: 'cyl', size: [0.045, 0.06], pos: [0, 0.075, 0.0], note: '人の上を飛ぶための安全装備' },
    ],
    weight: '+1.0 kg', time: '約20分 → 約12分', how: '機体は同じ設計のまま、装備を足す。夜や煙の中で働くので灯火と赤外線が要る。' },
  { id: 'farm', name: '農業', tagline: '田畑に薬剤や肥料をまく',
    up: ['arm', 'motor', 'prop', 'battery', 'frameBottom', 'landingGear', 'esc', 'pdb', 'wiring'],
    ghost: [
      { id: 'tank', name: '薬剤タンク（10 L）', shape: 'box', size: [0.16, 0.12, 0.16], pos: [0, -0.09, 0.0], note: '満タンで約10 kg。機体全体は別設計の大型機になる' },
      { id: 'nozzleL', name: 'ノズル', shape: 'cyl', size: [0.012, 0.04], pos: [0.19, -0.02, 0.19], note: 'アーム先端から噴霧' },
      { id: 'nozzleR', name: 'ノズル', shape: 'cyl', size: [0.012, 0.04], pos: [-0.19, -0.02, -0.19], note: 'アーム先端から噴霧' },
      { id: 'pump', name: 'ポンプ', shape: 'box', size: [0.05, 0.04, 0.05], pos: [0, -0.17, 0.0], note: '流量を調節する' },
    ],
    weight: '+10〜15 kg（機体ごと大型化）', time: '約20分 → 約8分（散布中）', how: '原理は同じだが、6〜8ローターの大型機として別に設計される。ジンバルとカメラは外す。' , drop: ['gimbal', 'camera', 'damper'] },
  { id: 'inspect', name: '点検', tagline: '橋やビルの壁を近くで撮る',
    up: ['gimbal', 'camera', 'gps', 'led', 'fc'],
    ghost: [
      { id: 'guardFR', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [0.194, 0.045, -0.194], note: '構造物への接触から守る' },
      { id: 'guardFL', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [-0.194, 0.045, -0.194], note: '' },
      { id: 'guardRR', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [0.194, 0.045, 0.194], note: '' },
      { id: 'guardRL', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [-0.194, 0.045, 0.194], note: '' },
      { id: 'upcam', name: '上向きカメラ', shape: 'box', size: [0.04, 0.03, 0.04], pos: [0.03, 0.055, -0.03], note: '橋の裏側を見る' },
      { id: 'sensor', name: '障害物センサー', shape: 'box', size: [0.03, 0.02, 0.02], pos: [0, 0.02, -0.10], note: '壁との距離を測って止まる' },
    ],
    weight: '+0.6 kg', time: '約20分 → 約15分', how: '橋の下ではGPSが届かないので、センサーとガードで壁に寄れるようにする。' },
  { id: 'photo', name: '空撮', tagline: '映像作品や測量の写真を撮る',
    up: ['gimbal', 'camera', 'damper', 'vtx'],
    ghost: [
      { id: 'bigcam', name: '大型カメラ（1インチ以上）', shape: 'box', size: [0.06, 0.05, 0.06], pos: [0, -0.095, -0.085], note: '画質のためにセンサーが大きい' },
      { id: 'nd', name: 'NDフィルター', shape: 'cyl', size: [0.02, 0.006], pos: [0, -0.085, -0.125], note: '明るすぎる昼間の光を減らす' },
    ],
    weight: '+0.3 kg', time: '約20分 → 約17分', how: '揺れを消すジンバルと、重いカメラを支えるダンパーが主役。機体そのものは今のまま。' },
  { id: 'school', name: '教育', tagline: '安全に練習して、仕組みを学ぶ',
    up: ['landingGear', 'led'],
    ghost: [
      { id: 'guardFR', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [0.194, 0.045, -0.194], note: '練習中の接触事故を防ぐ' },
      { id: 'guardFL', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [-0.194, 0.045, -0.194], note: '' },
      { id: 'guardRR', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [0.194, 0.045, 0.194], note: '' },
      { id: 'guardRL', name: 'プロペラガード', shape: 'ring', size: [0.17, 0.006], pos: [-0.194, 0.045, 0.194], note: '' },
    ],
    weight: '+0.2 kg', time: '約20分 → 約19分', how: 'カメラとジンバルは外して軽くし、ガードを付ける。中身はこの教材の機体そのもの。', drop: ['gimbal', 'camera', 'damper'] },
  { id: 'delivery', name: '配送', tagline: '荷物を運んで届ける',
    up: ['motor', 'prop', 'battery', 'frameBottom', 'arm', 'esc'],
    ghost: [
      { id: 'boxp', name: '荷物ボックス（2 kg）', shape: 'box', size: [0.14, 0.10, 0.14], pos: [0, -0.10, 0.0], note: '重心の真下に固定する' },
      { id: 'winch', name: 'ウインチ', shape: 'cyl', size: [0.02, 0.05], pos: [0, -0.04, 0.0], note: '着陸せずに荷物を下ろす' },
      { id: 'chute', name: 'パラシュート', shape: 'cyl', size: [0.045, 0.06], pos: [0, 0.075, 0.0], note: '人や家の上を飛ぶための安全装備' },
      { id: 'sensor', name: '障害物センサー', shape: 'box', size: [0.03, 0.02, 0.02], pos: [0, 0.02, -0.10], note: '電線や木を避ける' },
    ],
    weight: '+2.5 kg', time: '約20分 → 約9分', how: '荷物の分だけ推力と電池が要る。人の上を飛ぶので安全装備が増える。', drop: ['gimbal', 'camera', 'damper'] },
];

// ===== 素朴な質問 =====
// parts: 光らせる部品 / act: 押したときに起こす動作
const QUESTIONS = [
  { id: 'lift', q: 'なぜ浮くの？', parts: ['prop', 'motor'], act: { power: 0.5, air: true, flight: 'hover' },
    a: 'プロペラが空気を下に押すと、その反動で機体が上に押されます。4枚の合計が機体の重さと釣り合うと、空中で止まっていられます。' },
  { id: 'fwd', q: 'なぜ前に進むの？', parts: ['motor', 'fc'], act: { power: 0.5, air: true, flight: 'pitch' },
    a: '後ろ2つのモーターを少し速く、前2つを少し遅くすると機体が前に傾きます。傾くと、空気を押す向きも斜め後ろになるので、前へ進みます。' },
  { id: 'ccw', q: 'なぜ4枚とも同じ向きに回さないの？', parts: ['prop'], act: { power: 0.5, slow: true, arrows: true },
    a: 'プロペラを回すと、機体は反対向きに回されようとします。隣同士を逆向きにすると、その力が打ち消し合って機体は回りません。ゆっくり回して見ると、隣が逆向きなのがわかります。' },
  { id: 'time', q: '何分飛べる？', parts: ['battery'],
    a: 'この機体の例では、荷物なしで約20分です。バッテリーは機体で一番重い部品で、その重さを持ち上げるためにも電気を使います。だから電池を大きくしても、飛べる時間はそれほど伸びません。' },
  { id: 'rain', q: '雨の日は飛べる？', parts: ['fc', 'esc', 'battery'],
    a: '多くの機体は防水ではありません。基板や配線に水が入ると故障し、落ちることがあります。防滴の機体もありますが、風雨で姿勢も乱れやすいので、雨の日は飛ばさないのが基本です。' },
  { id: 'radio', q: '電波が切れたら？', parts: ['rx', 'gps', 'fc'],
    a: '受信機が電波を失うと、頭脳（FC）が「フェイルセーフ」を発動します。多くの機体はGPSを頼りに離陸した場所へ自動で帰ります。ただし設定と点検が前提で、万能ではありません。' },
  { id: 'where', q: 'どうやって自分の場所を知るの？', parts: ['gps', 'fc'],
    a: '上の白い円盤が衛星の電波を受けて位置を測ります。中には方位を知るためのコンパスも入っていて、モーターや電線の磁気から離すために棒の先に付けています。' },
  { id: 'weight', q: 'どれくらい重い？', parts: ['battery', 'frameBottom'],
    a: 'この機体の例で約2.4 kg、500 mLのペットボトル約5本分です。そのうち640 gがバッテリー。100 g以上の機体は国への登録が必要とされています。' },
  { id: 'crash', q: '落ちたらどこが壊れる？', parts: ['prop', 'landingGear', 'gimbal'], act: { theater: 'drop' },
    a: 'まずプロペラと脚、次にカメラを支えるジンバルです。フレームは強いので残ることが多い。「やってみる」で落として確かめられます。' },
  { id: 'oneout', q: 'モーターが1つ止まったら？', parts: ['motor', 'esc'], act: { theater: 'motorOut' },
    a: 'モーターが4つの機体は、1つ止まると姿勢を保てずに落ちます。6つ以上の機体なら、残りで降りられる場合があります。だから飛ぶ前にモーターの点検をします。' },
  { id: 'shake', q: 'カメラはなぜ揺れないの？', parts: ['gimbal', 'damper'],
    a: '3つの小さなモーターが、機体の揺れを瞬時に打ち消してカメラを水平に保ちます。さらにゴムのダンパーが細かい振動を吸収します。' },
  { id: 'night', q: '夜でも飛べる？', parts: ['led'],
    a: '夜に飛ばすには、原則として国の承認が要り、機体の向きがわかる灯火も必要です。この機体では前の左が赤、右が緑、後ろが白。遠くからでもどちらを向いているかわかります。' },
];
// 初回だけ浮かぶ一問
const FIRST_QUESTION = { q: '隣り合うプロペラは、なぜ逆向きに回るのでしょう？', hint: 'タップすると答えを機体が演じます', qid: 'ccw' };

// ===== やってしまったシアター =====
// setup: 見た目の違和感 / result: 離陸後に起きること / broken: 赤く点灯する部品 / prevent: どの点検で防げたか
const MISHAPS = [
  { id: 'propReverse', name: 'プロペラを1枚、逆向き用に付けた', short: 'プロペラ逆付け',
    setup: '前右（M1）に時計回り用のプロペラを付けてしまった。刻印は下向き。', flag: ['prop'], flagIdx: [0],
    result: 'M1だけ空気を上に押す（推力が下向き）。離陸した瞬間に前右へ倒れ、ひっくり返る。',
    broken: ['prop', 'motorMount', 'gimbal'], brokenIdx: { prop: [0, 3] },
    prevent: '飛行前点検「プロペラの向き（CW/CCW）と刻印が上を向いているか」で防げた。',
    checkPart: 'prop', physics: 'flipFR' },
  { id: 'escSwap', name: 'ESCの配線を2本入れ替えた', short: 'モーター順序違い',
    setup: '後右（M2）と後左（M3）の信号線をFCの逆の端子に挿した。頭脳は「M2を速く」と命じているのにM3が速くなる。', flag: ['esc'], flagIdx: [1, 2],
    result: '傾きを直そうとするほど逆に傾く。離陸直後に横転する。',
    broken: ['prop', 'landingGear', 'arm'], brokenIdx: { prop: [1, 2], landingGear: [1] },
    prevent: '組み立て後の「モーター順序と回転方向のテスト」（プロペラを外して1基ずつ回す）で防げた。',
    checkPart: 'esc', physics: 'rollOver' },
  { id: 'fcRotated', name: '頭脳（FC）を90°回して取り付けた', short: 'FC取付向き',
    setup: '基板の矢印が機首ではなく右を向いている。頭脳は「前」を「右」だと思っている。', flag: ['fc'], flagIdx: [0],
    result: '前に傾くと頭脳は「右に傾いた」と判断して左に直そうとする。補正が空回りし、激しく揺れて反転する。',
    broken: ['prop', 'gps', 'landingGear'], brokenIdx: { prop: [0, 1, 2, 3] },
    prevent: '設定画面で「機体を手で傾けて、画面の機体が同じ向きに傾くか」を見る確認で防げた。',
    checkPart: 'fc', physics: 'wobbleFlip' },
  { id: 'dirAndProp', name: 'モーターの回転方向とプロペラを両方逆にした', short: '反トルクの偏り',
    setup: '前右（M1）の相線を2本入れ替えて時計回りにし、プロペラも時計回り用に交換した。推力は出る。', flag: ['motor', 'prop'], flagIdx: [0],
    result: '浮くが、時計回りが3基・反時計回りが1基になり反トルクが釣り合わない。その場でクルクル回り続ける。',
    broken: [], brokenIdx: {},
    prevent: '「隣り合うモーターは逆回転」を1基ずつ確認する組み立て後テストで防げた。',
    checkPart: 'motor', physics: 'spin' },
  { id: 'drop', name: '1.5 mの高さから落とした', short: '落下',
    setup: 'バッテリーが切れて、1.5 mからそのまま落ちた。', flag: ['battery'], flagIdx: [0],
    result: '脚がしなって衝撃を受け、プロペラが弾け飛び、ジンバルが地面に当たる。',
    broken: ['prop', 'landingGear', 'gimbal', 'camera', 'damper'], brokenIdx: { prop: [0, 2] },
    prevent: '「残量30%で着陸」の運用と、離陸前のバッテリー電圧確認で防げた。',
    checkPart: 'battery', physics: 'drop' },
  { id: 'motorOut', name: 'モーターが1基止まった', short: '1基停止',
    setup: '後左（M3）のベアリングが焼き付いて回らなくなった。', flag: ['motor'], flagIdx: [2],
    result: 'M3の側が支えを失って落ち込み、反トルクの釣り合いも崩れて回転しながら傾いて落ちる。',
    broken: ['motor', 'prop', 'arm', 'landingGear'], brokenIdx: { motor: [2], prop: [2, 3], arm: [2] },
    prevent: '飛行前の「モーターを手で回して引っかかり・異音がないか」の点検で防げた。',
    checkPart: 'motor', physics: 'motorOut' },
];

// ===== 重さ・お金・重心 (パッケージ⑥) =====
// 質量 [g/個]。PARTS[key].count を掛けて合計する。内部部品(SUB の子)は親に含める:
// motor 95g はベル・ステーター・巻線・磁石・シャフト・ベース込み / prop 29g はナット3g+アダプター6g込み / battery 640g はセル込み。
const MASS = { frameTop: 45, frameBottom: 70, arm: 32, armClamp: 12, motorMount: 14, standoff: 3, screws: 30,
  motor: 95, prop: 29, esc: 26, fc: 30, pdb: 25, capacitor: 8, buzzer: 4,
  battery: 640, xt60: 10, balance: 4, strap: 12, wiring: 60, gps: 45, rx: 18, vtx: 30, led: 4, damper: 5,
  gimbal: 150, camera: 100, batteryTray: 40, remoteId: 25, regMark: 1, telemetry: 30, landingGear: 70 };
// 参考価格 [円/個]。複数通販サイトの中央値(2026年時点)の目安で、機種・時期で大きく変わる。
const PRICE = { frameTop: 6000, frameBottom: 8000, arm: 3200, armClamp: 900, motorMount: 1200, standoff: 150, screws: 1500,
  motor: 4500, prop: 900, propNut: 150, propAdapter: 400, esc: 3000, fc: 9000, pdb: 3500, capacitor: 300, buzzer: 400,
  battery: 16000, xt60: 300, balance: 200, strap: 400, wiring: 2500, gps: 7000, rx: 6000, vtx: 5000, led: 800, damper: 250,
  gimbal: 40000, camera: 20000, batteryTray: 2500, remoteId: 12000, regMark: 300, telemetry: 8000, landingGear: 2000 };
const SCALE_TEXT = { bottle: '500mlペットボトル', bottleG: 500, person: '幅は、大人が両手を広げた半分くらい（約85cm）',
  priceNote: '参考価格（2026年時点・国内通販の目安）。機種・時期で大きく変わります',
  overNote: 'モーターに余裕がありません。前に進む・風に逆らう余力が減ります',
  energyNote: '電池1本 ≒ スマホ約8台分の電気。飛べば約20分でなくなる',
  perMotor: (g) => `モーター1つが約 ${g} g（ペットボトル${(g / 500).toFixed(1)}本分）を持ち上げている` };
const PAYLOADS = [
  { id: 'none', name: 'なし', g: 0, pos: [0, 0, 0] },
  { id: 'cam', name: '追加カメラ +250g', g: 250, pos: [0, -0.12, -0.06] },
  { id: 'box', name: '荷物 1kg', g: 1000, pos: [0, -0.13, 0.02], ghost: { shape: 'box', size: [0.12, 0.08, 0.10] } },
];

// ===== 図鑑の豆知識 (パッケージ⑦): 1部品1文 =====
const TRIVIA = {
  frameTop: '上と下の板で挟むから、アームは1本ずつ外して交換できる。',
  frameBottom: '下の板は上より厚い。バッテリーと脚の荷重を受けるのはこちら。',
  arm: '中空の管は同じ重さの棒より曲がりにくい。だから中は空っぽ。',
  armClamp: '締めすぎるとカーボン管が割れ、ゆるいとアームが回る。トルクは製品の指定値（M3 で 1 N·m 前後）で。',
  motorMount: '2ピースの下側にネジ穴がある。長すぎるネジは巻線に届いて短絡する。',
  standoff: '支柱の長さが、上下の板の間に入る基板の高さを決める。',
  screws: '振動でゆるむのでネジ止め剤か、緩み止め付きナットを使う。',
  motor: '外側が回る「アウターランナー」。だから缶に触ってはいけない。',
  bell: '缶の内側に磁石が貼ってある。回っているのは磁石のほう。',
  stator: '固定子は動かない。動いて見えたら、取付ネジがゆるんでモーターごと回っている。',
  winding: '巻線は3本の線に分かれている。2本を入れ替えると回転方向が逆になる。',
  magnet: '落として缶をぶつけると磁石が欠ける。欠けると振動が出る。',
  shaft: 'ベアリングを指で回して「ザラッ」としたら交換のサイン。',
  motorBase: 'ベースの穴の間隔（16×19mm など）が、取り付けられるモーターマウントを決める。',
  prop: '刻印や色で CW／CCW を見分ける。モーターの回転と逆のプロペラを1枚でも付けると、離陸した瞬間にひっくり返る。',
  propNut: '「回転で締まる」ねじの製品では、CW 用と CCW 用でねじの向きが逆。取り違えると飛行中にゆるむ。',
  propAdapter: 'アダプターの軸径とプロペラの穴径が合っていないと、芯がずれて振動する。',
  esc: 'ESC は電流を毎秒数万回オンオフして、モーターの速さを作っている。',
  fc: '毎秒数千回、傾きを測って直す。人が手で同じことをするのは不可能。',
  pdb: '1枚の基板で太い電流を4本の ESC に分ける。ここが焼けると全部止まる。',
  capacitor: 'モーターが作る電圧の波を吸収する。無いと FC が誤作動することがある。',
  buzzer: '草むらに落ちた機体を探すのは、この小さな音。',
  battery: '重さの4分の1が電池。飛行時間を伸ばす一番の近道は「軽くする」。',
  cells: '6枚のセルの電圧差が 0.05V を超えたら要注意。バランス充電で揃えてから使う。',
  xt60: '黄色いコネクタは 60A 用。焼けて茶色くなっていたら交換。',
  balance: '細い線はセルを1枚ずつ測るため。充電器はこれで各セルを揃える。',
  strap: '面ファスナーのストラップ2本で 640g を支える。1本だと飛行中にずれる。',
  wiring: '3本のモーター線をねじるのは、電気のノイズを外に出さないため。',
  gps: '衛星の電波は上から来て、中のコンパスはモーターの磁気を嫌う。だから棒の先の一番高い所に載せる。',
  rx: '受信機のアンテナは2本を 90° に開く。どちらかが必ず送信機を向くように。',
  vtx: '映像送信機は熱くなる。風が当たる場所に置くのはそのため。',
  led: '前が赤と緑、後ろが白は、飛行機の灯火にならった例。遠くから向きがわかるようにするのが目的。',
  damper: 'ゴムのダンパーがモーターの細かい振動をカメラに伝えない。',
  gimbal: '3つのモーターが機体の傾きを打ち消す。だから映像が水平のまま。',
  camera: 'カメラは機体の中で一番揺れに弱い部品。だから一番下に、ゴムの上に載る。',
  batteryTray: 'トレイの前後どこに電池を置くかで重心が決まる。',
  remoteId: 'リモートIDは機体の「ナンバープレート」を電波で出す装置。',
  regMark: '登録記号は外から読める場所に、消えない方法で表示する。',
  telemetry: 'テレメトリーは機体から地上へ「電池が少ない」などを知らせる無線。',
  landingGear: '脚は「壊れて機体を守る」部品。曲がったら交換で正解。',
};

// ===== もしもの5場面 (パッケージ⑩): 外の状況。機体ができることと人がやることを対で =====
const WHATIF_STAGES = ['状況', '機体の反応', '働く部品', 'できること・やること'];
const WHATIF = [
  { id: 'signal', name: '電波が切れた', icon: '📡', short: '操縦の指示が届かない',
    intro: '送信機との電波が届かなくなった。操縦の指示が機体に届かない。',
    reaction: '機体は「指示が来ない」ことを自分で検知し、あらかじめ決めた動き（多くの機種では、離陸した場所へ帰って降りる）に切り替える。',
    motion: 'rth', parts: ['rx', 'fc', 'gps', 'motor'],
    partNotes: { rx: '受信機が「電波が途切れた」と判断する', fc: 'FC（頭脳）が、覚えていた離陸地点へ戻るフェイルセーフに切り替える', gps: '今いる場所を測り、離陸地点までの向きと距離がわかる', motor: '帰る向きへ機体を進める' },
    can: ['電波が切れたことを自分で検知する', '設定に従い、離陸地点へ戻る／その場で降りる', '電波が戻れば操縦を受け付ける'],
    human: ['飛ばす前にフェイルセーフの設定を確認する', '目視で機体を追い続ける', '周囲の人に「戻ってきます」と声をかける', '帰還経路に人や障害物がないか見る'],
    caveat: '帰還の動きは機種と設定で異なり、GPSが使えないと働かない。「設定と点検が前提」で、万能ではない。' },
  { id: 'battery', name: '電池が少ない', icon: '🔋', short: '残量が減ってきた',
    intro: '飛行中に電池の残りが減ってきた。',
    reaction: '機体は電圧を常に測っていて、決めた値を下回ると警告する。多くの機種では、さらに下がると自動で降下を始める。',
    motion: 'landSlow', parts: ['battery', 'pdb', 'fc', 'buzzer', 'telemetry'],
    partNotes: { battery: '電圧が下がる', pdb: '電圧を測る回路が値を FC（頭脳）へ送る', fc: 'FC（頭脳）が警告と自動降下を判断する', buzzer: '音で知らせる', telemetry: '地上局（送信機や画面）に残量を知らせる' },
    can: ['電圧を常に測って残量を推定する', '決めた値で警告を出す', 'さらに下がれば自動で降下・着陸する'],
    human: ['飛ばす前に満充電と電圧差を確認する', '警告が出たらすぐ戻す（粘らない）。目安は残量 30% で着陸', '着陸できる場所を常に把握しておく'],
    caveat: '寒い日にスマホが急に切れるのと同じで、寒い日や古い電池は残量表示より早く落ちる。自動降下は「安全な場所」を選んでくれるわけではない。' },
  { id: 'gps', name: 'GPSを見失った', icon: '🛰️', short: '衛星が見えない場所で',
    intro: '建物の陰や橋の下で、衛星の電波が届かなくなった。',
    reaction: '位置は分からなくなるが、傾きは分かる。機体は水平を保ったまま、風に少しずつ流される。',
    motion: 'driftHold', parts: ['gps', 'fc', 'motor'],
    partNotes: { gps: '衛星が見えなくなる', fc: 'FC（頭脳）が位置の保持をあきらめ、姿勢の保持だけ続ける', motor: '傾きを直す動きは続く' },
    can: ['姿勢（傾き）を保ち続ける', '位置が保てないことを画面に知らせる', 'GPSが戻れば位置の保持に復帰する'],
    human: ['流される方向を見て、手で位置を直す', '建物・橋の近くでは最初から手動の練習をしておく', '無理をせず、開けた場所へ戻して降ろす'],
    caveat: 'GPSなしでも飛べるかは機種と設定次第。屋内や高い建物の間では最初から「位置保持は効かない」前提で計画する。' },
  { id: 'wind', name: '風が強い', icon: '🌬️', short: '急に風が強くなった',
    intro: '急に風が強くなった。',
    reaction: '機体は流されないように風上へ傾いて踏ん張る。傾きを作る一瞬は風下側を強く回し、傾いたままの間は4つ全部が少しずつ余分に働く。その分、電池の減りが早くなる。',
    motion: 'wind', parts: ['fc', 'motor', 'prop', 'battery'],
    partNotes: { fc: 'FC（頭脳）が流されたぶんを検知して傾きを命じる', motor: '傾きを保つために4つとも少し余分に回る', prop: '傾けたぶんの推力で風に逆らう', battery: '踏ん張る分だけ消費が増える' },
    can: ['ある程度の風なら位置を保つ', '傾いて踏ん張る（合計の力を増やす）'],
    human: ['飛ばす前に風速を確認し、機体の限界の6〜7割で判断する', '風が強まったら風下に人がいない場所へ移す', '早めに降ろす。粘ると電池が先に尽きる'],
    caveat: '耐風性能は機種ごとに決まっていて、突風はその値を超えることがある。上空は地上より風が強い。' },
  { id: 'person', name: '人が近づいた', icon: '🚶', short: '見物の人が歩いてくる',
    intro: '見物の人が機体のほうへ歩いてきた。',
    reaction: '機体には人を避ける仕組みはない（あっても万能ではない）。できるのは、操縦者と補助者が止めること。',
    motion: 'person', parts: ['led', 'buzzer', 'prop'],
    partNotes: { led: '灯火で「動いている機体」だと知らせる', buzzer: '音で注意を引く', prop: '回っている間は触れてはいけない部分' },
    can: ['灯火と音で「動いている」ことを知らせる', '操縦者の指示ですぐ離れる・降りる'],
    human: ['補助者が近づく人を止める', '離着陸場所にロープや目印を置く', '人が来たら機体を離す、または降ろして止める', '回っているプロペラに近づかない'],
    caveat: '第三者の上は原則として飛ばさない（飛ばすには国の許可・承認が必要とされています）。近くを飛ばす場合も、機体の性能ではなく運用（補助者・区画・手順）で守る。' },
];

// ===== 言語 (パッケージ⑧): やさしい日本語 / English。段階1 = タブ・主要ボタン・8部品・12質問 =====
const I18N = {
  ja: { tabs: { see: 'みる', fly: 'とばす', use: 'つかう', mishap: 'もしも', expert: '専門' }, depth: { simple: 'はじめて', full: 'くわしく' }, ask: 'きく', power: '▶ プロペラを回す', stop: '■ 止める', views: { iso: '斜', front: '前', top: '上', side: '横', inside: '内', labels: '名' }, big: '大', speak: '読み上げ',
    ui: { parts: '部品一覧', script: '台本', focus: '注目', more: 'くわしく見る', explode: '分解', look: '見え方', normal: 'ふつう', xray: 'すけて見る', wire: '線だけ', cut: '切って見る' }, sec: { structure: '構造', trivia: '豆知識', role: '役割', analogy: 'たとえるなら' }, parts: {}, questions: {} },
  easy: { tabs: { see: 'みる', fly: 'とばす', use: 'つかう', mishap: 'もしも', expert: 'せんもん' }, depth: { simple: 'はじめて', full: 'くわしく' }, ask: 'きく', power: '▶ プロペラを 回す', stop: '■ とめる', views: { iso: 'ななめ', front: 'まえ', top: 'うえ', side: 'よこ', inside: 'なか', labels: 'なまえ' }, big: 'おおきく', speak: 'よみあげ',
    ui: { parts: 'ぶひんの リスト', script: 'だいほん', focus: 'ちゅうもく', more: 'くわしく みる', explode: 'ばらばら', look: 'みえかた', normal: 'ふつう', xray: 'すけて みる', wire: 'せんだけ', cut: 'きって みる' }, sec: { structure: 'つくり', trivia: 'まめちしき', role: 'やくわり', analogy: 'たとえると' },
    parts: {
      prop:        { name: 'プロペラ',           role: 'まわって、空気を 下に おします。おした ぶんだけ、ドローンは 上に おされて うきます。', analogy: 'せんぷうきを 下に むけて、じぶんが ふわっと うくような もの' },
      motor:       { name: 'モーター',           role: 'プロペラを まわす 力の もとです。1分に 何千回も まわります。', analogy: 'おもちゃの モーターを、もっと つよく、もっと しずかに したもの' },
      arm:         { name: 'アーム（うで）',     role: 'モーターを、ドローンの まん中から おなじ きょりに ささえる ぼうです。', analogy: 'シーソーの いた。まん中から 左右が おなじ 長さだから、つりあう' },
      frameTop:    { name: 'フレーム（ほね）',   role: 'ドローンの ほねぐみです。ぜんぶの ぶひんが ここに つきます。', analogy: '人の せぼね' },
      battery:     { name: 'バッテリー（でんち）', role: 'ぜんぶの 電気の もとです。ドローンで いちばん おもい ぶひんです。ねだんも 高いです。', analogy: 'スマホ 8だいぶんの でんきを、1つに まとめた もの' },
      fc:          { name: 'あたま（FC）',        role: 'ドローンの あたまです。かたむきを まばたきより はやく 何千回も はかって、4つの モーターの はやさを きめます。', analogy: 'じてんしゃに のるときの「からだの バランス」。たおれそうに なると、かってに なおす' },
      landingGear: { name: 'あし',               role: 'おりる とき、ドローンと カメラを じめんから まもる あしです。', analogy: 'ひこうきの タイヤ。でも ころがらないで、そりのように すべる' },
      camera:      { name: 'カメラ',             role: '上から しゃしんや ビデオを とります。ゆれない ように、ゴムに ぶらさがって います。', analogy: 'スマホの カメラを、ゆれない だいに のせた もの' },
    },
    questions: { lift: 'どうして うくの？', fwd: 'どうして 前に すすむの？', ccw: 'どうして 4まい ぜんぶ おなじ むきに まわさないの？', time: '何分 とべるの？', rain: '雨の日は とべるの？', radio: 'でんぱが きれたら どうなるの？', where: 'どうやって じぶんの ばしょを 知るの？', weight: 'どのくらい おもいの？', crash: 'おちたら どこが こわれるの？', oneout: 'モーターが 1つ とまったら？', shake: 'カメラは どうして ゆれないの？', night: 'よるも とべるの？' } },
  en: { tabs: { see: 'Look', fly: 'Fly', use: 'Use', mishap: 'What if', expert: 'Expert' }, depth: { simple: 'Basic', full: 'Details' }, ask: 'Ask', power: '▶ Spin props', stop: '■ Stop', views: { iso: '3D', front: 'Front', top: 'Top', side: 'Side', inside: 'Inside', labels: 'Name' }, big: 'Big', speak: 'Read aloud',
    ui: { parts: 'Parts', script: 'Script', focus: 'Focus', more: 'More details', explode: 'Explode', look: 'View', normal: 'Normal', xray: 'X-ray', wire: 'Lines', cut: 'Cut' }, sec: { structure: 'Structure (Japanese)', trivia: 'Fun fact (Japanese)', role: 'Role', analogy: 'Like…' },
    parts: {
      prop:        { name: 'Propeller', role: 'It spins and pushes air down. The air pushes back, and that lifts the drone.', analogy: 'Like pointing a fan at the floor until you float.' },
      motor:       { name: 'Motor',     role: 'It spins the propeller — thousands of turns every minute.', analogy: 'A toy motor, but stronger and quieter.' },
      arm:         { name: 'Arm',       role: 'It holds each motor at the same distance from the center.', analogy: 'A seesaw: same length on both sides, so it balances.' },
      frameTop:    { name: 'Frame',     role: 'The skeleton. Every part is attached to it.', analogy: 'Your spine and ribs.' },
      battery:     { name: 'Battery',   role: 'The source of all power. The heaviest part, and one of the most expensive.', analogy: 'About the energy of 8 phone batteries in one pack.' },
      fc:          { name: 'Brain (FC)', role: 'It measures the tilt thousands of times a second and sets the speed of the 4 motors.', analogy: 'Your sense of balance on a bicycle: it corrects you before you fall.' },
      landingGear: { name: 'Legs',      role: 'They protect the body and the camera when the drone lands.', analogy: 'Like airplane wheels, but they slide instead of rolling.' },
      camera:      { name: 'Camera',    role: 'It takes photos and video from above. It hangs on rubber so it does not shake.', analogy: 'A phone camera on a steady mount.' },
    },
    questions: { lift: 'How does it stay up?', fwd: 'How does it move forward?', ccw: 'Why not spin all 4 the same way?', time: 'How many minutes can it fly?', rain: 'Can it fly in the rain?', radio: 'What if the radio link is lost?', where: 'How does it know where it is?', weight: 'How heavy is it?', crash: 'What breaks in a crash?', oneout: 'What if one motor stops?', shake: "Why doesn't the camera shake?", night: 'Can it fly at night?' } },
};

// ===== 授業・説明会モード (パッケージ⑨): 台本は確定文。法令は断定しない =====
const LESSONS = [
  { id: 'class45', name: '45分授業', audience: '中学・高校・初心者', total: 45, depth: 'simple',
    review: ['ドローンが浮く理由を、ひとことで書いてみよう。', '隣どうしのプロペラが逆に回るのはなぜ？', '飛ばす前に、自分ならどこを点検する？（2つ。理由も）'],
    steps: [
      { t: 0, title: '眺める', min: 5, view: 'iso', act: { alive: true },
        say: '今日はドローンの中身を見ます。まず 1 分、何も説明せずに眺めてください。気づいたことを隣の人と 1 つずつ言い合ってください。',
        ask: '「これは何のためにあると思う？」と指をさして聞いてみよう。', expect: 'プロペラ・電池・カメラなど。答えが違っていてもここでは正さない。生徒の端末で開けるなら、この1分は各自の画面で。' },
      { t: 5, title: '4枚のプロペラ', min: 6, view: 'top', act: { question: 'ccw' },
        say: '上から見ます。プロペラは 4 枚。となり同士は逆向きに回っています。まず予想を隣の人と言い合ってから、画面の「なぜ？」を読みます。',
        ask: '全部同じ向きに回したら、機体はどうなると思う？（先に予想）', expect: '機体そのものが逆向きに回ってしまう（反トルク）。だから 2 枚ずつ逆にして打ち消す。体で試すなら: 4人が輪になって全員同じ向きに歩くと輪が回る。2人ずつ逆に歩くと止まる（30秒）。「ゆっくり」で隣が逆向きなのを見せて締める。' },
      { t: 11, title: 'なぜ浮くのか', min: 6, view: 'front', act: { power: 0.5, air: true, flight: 'hover' },
        say: 'プロペラが空気を下に押しています。青い流れが空気です。押した分だけ、機体は上に押し返されます。',
        ask: '4 枚の押す力の合計が、機体の重さより小さかったら？', expect: '浮かない。ちょうど同じで空中に止まる。大きいと上がる。機体は約 2.4 kg なので、モーター 1 つが約 600 g、ペットボトル 1 本強を持ち上げている。' },
      { t: 17, title: '頭脳が直す', min: 7, view: 'iso', act: { power: 0.5, sticks: false, coach: '機体を指ではじいてみよう' },
        say: '機体を指ではじいてください。傾いた分を、頭脳（FC）がモーターの速さを変えて直します。人間には速すぎてできません。前に出て 3〜4 人、交代でやってみましょう。',
        ask: 'どのモーターが速くなった？ %の表示を見て。', expect: '押されて下がった側のモーターが速くなる（110% など）。「どっちが速くなるか」を予想させてからはじくと当たり外れで盛り上がる。' },
      { t: 24, title: '中を開ける', min: 7, view: 'iso', act: { explode: 1 },
        say: 'ここからは分解します。上から順に、プロペラ・モーター・アーム・フレーム・基板・電池。スライダーは生徒に動かしてもらいます。',
        ask: '一番重い部品はどれだと思う？', expect: '電池。全体の 4 分の 1 くらい（640 g）。「つかう」→「重さ・お金」の積み上げバーで一目でわかる。だから軽くするのが飛行時間を伸ばす近道。' },
      { t: 31, title: 'やってしまった', min: 7, view: 'iso', act: { theater: 'propReverse' },
        say: 'プロペラを 1 枚、逆向き用に付けてしまいました。離陸するとどうなるか、見てください。',
        ask: 'どの点検をしていれば防げた？', expect: 'プロペラの向き（CW/CCW）と刻印が上を向いているか。飛行前点検で見つかる。' },
      { t: 38, title: 'ふたりクイズとふりかえり', min: 7, view: 'iso', act: { quiz: true },
        say: '最後に隣の人とクイズ。画面は答えを出しません。光った部品の名前と役割を、相手に説明してください。',
        ask: '（ふりかえりカードの 3 問）', expect: 'カードは印刷して配る。答えは書かせて回収しない（自分のメモにする）。' },
    ] },
  { id: 'town10', name: '10分住民説明会', audience: '地域の方・保護者', total: 10, depth: 'simple',
    review: ['ドローンが「落ちにくい」ための仕組みを 1 つ挙げてください。', '飛行中に電波が切れたとき、機体は何をするように設定されていますか。', '私たちが安全のためにお願いしたいことは何でしたか。'],
    steps: [
      { t: 0, title: 'これが飛ぶ機体です', min: 2, view: 'iso', act: { alive: true },
        say: 'この地域で飛ばすドローン（機体）と同じ型です。重さは約 2.4 kg、500ml のペットボトル約 5 本分。落ちれば人にけがをさせる重さです。回っているプロペラの先端はホバリング中でも時速約 260 km（新幹線並み）。だからこそ、どう落ちにくくしているか、落ちないためにどう備えるかをお話しします。',
        ask: '（問いかけなし。眺めてもらう）', expect: '' },
      { t: 2, title: 'なぜ落ちにくいのか', min: 3, view: 'iso', act: { power: 0.5, coach: '機体を指ではじいてみよう' },
        say: '傾いても、頭脳がモーターの速さを変えて自分で直します。指ではじいても戻ります。ただし機械ですので「絶対に落ちない」とは言えません。だから次の 2 つを必ずしています。',
        ask: '「風が吹いたら？」と聞かれたら: 機体の限界より弱い風速（目安は限界の6〜7割）でしか飛ばさず、強まれば早めに降ろします、と答える。', expect: '' },
      { t: 5, title: 'もしも電波が切れたら', min: 3, view: 'iso', act: { whatif: 'signal' },
        say: '操縦の電波が切れると、機体は自分で気づいて、あらかじめ決めた動き（離陸地点へ戻る）をします。これは設定と点検が前提で、万能ではありません。私たちがお願いしたいことは、飛行中に機体へ近づかないこと、補助者の指示に従うことです。',
        ask: '「落ちたら誰が責任を取るの？」と聞かれたら: 飛行には責任者（操縦者）がいます。責任者の名前・連絡先・保険の有無は、ここで自分の言葉で伝える。', expect: '台本では断定しない。保険・許可承認の有無は運用者ごとに違うので、発表者が事実だけを述べる。' },
      { t: 8, title: '飛ばす前に必ずすること', min: 2, view: 'iso', act: { select: 'prop' },
        say: 'プロペラの向き・電池・ネジ・脚を毎回点検します。壊れる前に見つけるのが仕事です。人の少ない場所と時間を選ぶことも、点検と同じ「飛ばす前の仕事」です。',
        ask: '質問があればどうぞ。この機体の画面は、どなたでも同じ URL で開けます。', expect: '' },
    ] },
];
// 部品めぐりの順（外→内）
const TOUR_ORDER = ['prop','propNut','propAdapter','motor','bell','magnet','winding','stator','shaft','motorBase','motorMount','arm','armClamp','frameTop','standoff','frameBottom','screws','esc','pdb','capacitor','xt60','battery','cells','balance','strap','batteryTray','wiring','fc','buzzer','gps','rx','vtx','telemetry','remoteId','led','regMark','damper','gimbal','camera','landingGear'];

// 豆知識の「確かめる」: 読んだ直後に機体が演じる（キーが無い部品はボタンなし）
const TRIVIA_ACT = {
  arm: { explode: 1 }, frameTop: { explode: 1 }, standoff: { explode: 1 },
  prop: { question: 'ccw' }, propNut: { question: 'ccw' }, motor: { mode: 'cut' }, bell: { mode: 'cut' }, stator: { mode: 'cut' }, magnet: { mode: 'cut' }, shaft: { mode: 'cut' },
  winding: { theater: 'dirAndProp' }, esc: { theater: 'escSwap' }, motorMount: { theater: 'propReverse' }, landingGear: { theater: 'drop' }, strap: { theater: 'drop' },
  fc: { fly: true, coach: '機体を指ではじいてみよう。頭脳が直します' },
  battery: { scale: true }, cells: { scale: true }, xt60: { scale: true }, batteryTray: { scale: true },
  led: { question: 'night' }, damper: { question: 'shake' }, gimbal: { question: 'shake' }, camera: { question: 'shake' },
  rx: { whatif: 'signal' }, gps: { whatif: 'gps' }, telemetry: { whatif: 'battery' }, buzzer: { whatif: 'battery' }, pdb: { whatif: 'battery' },
  wiring: { mode: 'xray' }, capacitor: { mode: 'xray' },
};

// ===== 1000フライト早送り (パッケージ⑫): 消耗の区分と交換目安[フライト回数の幅]。典型例であり順番を見るためのもの =====
const WEAR = {
  battery:     { cls: 'must',  lo: 150,  hi: 300,  effect: '容量が2割減る' },
  prop:        { cls: 'must',  lo: 100,  hi: 300,  effect: '縁の欠け・振動' },
  xt60:        { cls: 'must',  lo: 200,  hi: 400,  effect: '接点の焼け・はんだの微小クラック' },
  shaft:       { cls: 'wear',  lo: 300,  hi: 600,  effect: 'ベアリングのガタ・異音' },
  damper:      { cls: 'wear',  lo: 200,  hi: 500,  effect: 'ゴムが硬くなり振動が伝わる' },
  strap:       { cls: 'wear',  lo: 150,  hi: 400,  effect: '面ファスナーが甘くなる' },
  screws:      { cls: 'wear',  lo: 300,  hi: 600,  effect: '振動でゆるむ' },
  propNut:     { cls: 'wear',  lo: 300,  hi: 600,  effect: 'ねじ山の摩耗' },
  balance:     { cls: 'wear',  lo: 300,  hi: 800,  effect: '接触不良' },
  capacitor:   { cls: 'wear',  lo: 800,  hi: 1500, effect: '電解液の劣化' },
  wiring:      { cls: 'wear',  lo: 600,  hi: 1200, effect: '曲げ疲労で芯線が切れる' },
  landingGear: { cls: 'crash', lo: 200,  hi: 600,  effect: '着陸の衝撃で曲がる' },
  arm:         { cls: 'crash', lo: 400,  hi: 1000, effect: '根元の白化（層間はく離）' },
  gimbal:      { cls: 'crash', lo: 300,  hi: 800,  effect: '軸のガタ' },
  camera:      { cls: 'crash', lo: 500,  hi: 1000, effect: 'レンズの傷・衝撃' },
  motorMount:  { cls: 'crash', lo: 500,  hi: 1200, effect: '転倒で割れる' },
  esc:         { cls: 'robust', lo: 1500, hi: 3000, effect: '熱で寿命が決まる' },
  motor:       { cls: 'robust', lo: 1000, hi: 2500, effect: '巻線の絶縁劣化' },
  winding:     { cls: 'robust', lo: 1000, hi: 2500, effect: '絶縁劣化' },
  fc:          { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, pdb: { cls: 'robust', lo: 2000, hi: 5000, effect: '' },
  frameTop:    { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, frameBottom: { cls: 'robust', lo: 2000, hi: 5000, effect: '' },
  armClamp:    { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, standoff: { cls: 'robust', lo: 3000, hi: 6000, effect: '' },
  bell:        { cls: 'robust', lo: 1500, hi: 3000, effect: '' }, stator: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, magnet: { cls: 'robust', lo: 1500, hi: 3000, effect: '欠けは事故時' }, motorBase: { cls: 'robust', lo: 3000, hi: 6000, effect: '' },
  gps: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, rx: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, vtx: { cls: 'robust', lo: 1500, hi: 3000, effect: '熱' }, led: { cls: 'robust', lo: 2000, hi: 5000, effect: '' },
  telemetry: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, remoteId: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, regMark: { cls: 'robust', lo: 3000, hi: 6000, effect: '色あせ' }, batteryTray: { cls: 'robust', lo: 2000, hi: 5000, effect: '' },
  propAdapter: { cls: 'robust', lo: 1500, hi: 3000, effect: '' }, buzzer: { cls: 'robust', lo: 2000, hi: 5000, effect: '' }, cells: { cls: 'must', lo: 150, hi: 300, effect: '容量低下' },
};
